### ISSUE TITLE
City: Original - where does elements come from? 

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#106]
Used jar file from "Usage description". After generating a model, viewed the console and noticed, that there are more elements loaded, than there exist. 

For example I've activated all the elements via package explorer. Console shows errors for 983 elements. 
![Screenshot_6](https://user-images.githubusercontent.com/14137015/66378473-c8469f00-e9b3-11e9-9b05-f515007c9b86.png)

Found a place in code, which loads model elements and checked also there how many requests are made and there was also the number 983. If we check in Neo4j Dashboard we'll see, that there are:

- Districts: 5;
- Building: 87;

- BuildingSegments (there are 300, but they are not used in Original City model generation, right?)

So where does all elements come from?

**Comment by naraesk** [comment]
The metadata.json contains all elements (methods, attributes …) whether they are displayed or not. So in the model.html we load much more than the 5 districts and 87 buildings. Not sure why it is exactly 983, I guess we get multiple errors for each element (maybe due to relations). It's a bug anyway, model.html is a mess

**Comment by VlaD-T** [comment]
Ok, thanks.
